version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjusted to match the Docker run command and the Dockerfile's EXPOSE
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/processx
      - CACHE_URL=redis://cache:6379
    depends_on:
      - db
      - cache
    networks:
      - processx-network

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=processx
    networks:
      - processx-network

  cache:
    image: redis:latest
    networks:
      - processx-network

networks:
  processx-network:
    driver: bridge

volumes:
  pgdata:
